name: Run Playwright Tests (Desktop App)

on:
  workflow_dispatch:  # Run manually from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Electron dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libnss3 libxss1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Download AppImage
        run: |
          curl -L -o DevaidStarter_Dev-4.1.1.AppImage https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1/DevaidStarter_Dev-4.1.1.AppImage
          chmod +x ./DevaidStarter_Dev-4.1.1.AppImage

      - name: List files in workspace
        run: ls -lh

      - name: Launch AppImage
        run: |
          ./DevaidStarter.AppImage &
          sleep 5  # Adjust wait time if needed

      - name: Run Playwright tests in Xvfb
        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
