name: Run Electron App Tests

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y xvfb libgtk-3-dev libnss3 libasound2

      - name: Instalar dependencias del proyecto
        run: |
          npm ci

      - name: Instalar navegadores de Playwright
        run: |
          npx playwright install --with-deps

      - name: Ejecutar app Electron y tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npm run test

      - name: Guardar reporte de resultados (si tienes uno)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
