name: Electron App Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Electron App
      run: |
        wget https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1-dev/DevaidStarter_Dev-4.1.1.AppImage.zip -O app.zip
        unzip app.zip -d app
        chmod +x app/DevaidStarter_Dev-4.1.1.AppImage
        mkdir -p app
        
    - name: Install system dependencies (Ubuntu 24.04 compatible)
      run: |
        sudo apt-get update
        # Updated package names for Ubuntu 24.04
        sudo apt-get install -y \
          libgtk-4-1 \
          libnss3 \
          libasound2t64 \
          libxss1 \
          libgbm1 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libwayland-client0 \
          libwayland-server0 \
          libxshmfence1 \
          fuse3 \
          libfuse2
        
        # AppImage specific setup
        sudo modprobe fuse
        sudo groupadd fuse
        sudo usermod -a -G fuse $USER
        sudo chmod 660 /dev/fuse
        
    - name: Set up virtual display
      run: |
        sudo apt-get install -y xvfb libxv1 x11-utils
        Xvfb :99 -screen 0 1280x1024x24 >/dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    - name: Debug AppImage execution
      run: |
        # Verify the AppImage can run
        ./app/DevaidStarter_Dev-4.1.1.AppImage --version || true
        # Check dependencies
        ldd ./app/DevaidStarter_Dev-4.1.1.AppImage || true
        
    - name: Run Playwright tests
      run: npx playwright test --trace on
      env:
        ELECTRON_ENABLE_LOGGING: 1
        DEBUG: electron*
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7