name: Test AppImage Launch

on:
  workflow_dispatch: # Run manually from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install GUI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb libgtk-3-0 libnss3 libasound2 libxss1 libatk-bridge2.0-0 \
            libgtk-3-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 \
            libgbm1 libpango-1.0-0 libcairo2 libxext6 libxfixes3 libxrender1 \
            libxcb1 libxcb-dri3-0 libdrm2 libatspi2.0-0 libxinerama1 libxcursor1

      - name: Download AppImage
        run: |
          mkdir app
          curl -L -o app/DevaidStarter.AppImage https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1/DevaidStarter_Dev-4.1.1.AppImage
          chmod +x app/DevaidStarter.AppImage

      - name: Run AppImage with xvfb
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' \
            ./app/DevaidStarter.AppImage &

          # Wait a few seconds to see if it starts up without crashing
          sleep 10

          # Check if the process is still running
          pgrep -f DevaidStarter.AppImage || (echo "AppImage failed to launch" && exit 1)
