name: Run AppImage (No GUI)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Download AppImage
        run: |
          curl -L -o app.AppImage https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1/DevaidStarter_Dev-4.1.1.AppImage
          chmod +x app.AppImage

      - name: Extract AppImage (bypass FUSE)
        run: |
          ./app.AppImage --appimage-extract
          ls -l squashfs-root

      - name: Run extracted binary (headless)
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' ./squashfs-root/AppRun || true
