name: Electron App Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04  # Explicitly use Ubuntu 24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Electron App
      run: |
        wget https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1-dev/DevaidStarter_Dev-4.1.1.AppImage.zip -O app.zip
        unzip app.zip -d app
        chmod +x app/DevaidStarter_Dev-4.1.1.AppImage
        mkdir -p app  # Ensure app directory exists
        
    - name: Install system dependencies (Ubuntu 24.04 specific)
      run: |
        sudo apt-get update
        # Updated package names for Ubuntu 24.04
        sudo apt-get install -y libgtk-4-1 libnss3 libasound2t64 libxss1 libgbm1
        sudo apt-get install -y fuse3 libfuse2
        sudo modprobe fuse
        sudo groupadd fuse
        sudo usermod -a -G fuse $USER
        sudo chown root:fuse /dev/fuse
        sudo chmod 660 /dev/fuse
        
    - name: Verify AppImage
      run: |
        ls -la app/
        file app/DevaidStarter_Dev-4.1.1.AppImage
        ./app/DevaidStarter_Dev-4.1.1.AppImage --version || true
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # Updated to Node.js 20 (LTS)
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    - name: Start Xvfb (virtual framebuffer)
      run: |
        Xvfb :99 -screen 0 1280x1024x24 &
        sleep 3
        export DISPLAY=:99
        
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Generate HTML report
      if: always()
      run: npx playwright show-report
      
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-html-report
        path: playwright-report/
        retention-days: 7