name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Linux dependencies for Electron
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libasound2t64 \
          libxss1 \
          libgtk-3-0 \
          libfuse2 \
          dbus-x11

    - name: Download AppImage
      run: |
        mkdir -p app
        curl -L -o ./app/DevaidStarter_Dev-4.1.1.AppImage https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1/DevaidStarter_Dev-4.1.1.AppImage
        chmod +x ./app/DevaidStarter_Dev-4.1.1.AppImage

    - name: Make start-electron.sh executable
      run: chmod +x ./start-electron.sh

    - name: Install dependencies
      run: npm ci

    - name: Start Electron App
      run: ./start-electron.sh    

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npx playwright test
