name: Playwright Tests with AppImage

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Download DevaidStarter AppImage Release
        run: |
          curl -L -o DevaidStarter_Dev-4.1.1.AppImage.zip "https://github.com/RMateosAyesa/actionsDemo/releases/download/v4.1.1-dev/DevaidStarter_Dev-4.1.1.AppImage.zip"
          unzip DevaidStarter_Dev-4.1.1.AppImage.zip -d ./app
          chmod +x ./app/DevaidStarter_Dev-4.1.1.AppImage

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
